version: 2.1

jobs:
  build:
    machine:
      image: default
    steps:
      - checkout
      - run: curl -fsSL https://deno.land/install.sh | sh
      - run: /home/circleci/.deno/bin/deno upgrade --version 1.39.0
      - run:
          name: Run lint
          command: |
            cd supabase/functions/user-actions
            /home/circleci/.deno/bin/deno task lint
      - run:
          name: Run fmt
          command: |
            cd supabase/functions/user-actions
            /home/circleci/.deno/bin/deno task fmt --check

      - run: curl -fsSL https://deb.nodesource.com/setup_21.x | sudo -E bash - && sudo apt-get install -y nodejs
      - run: npx supabase init
      - run: npx supabase start -x gotrue,realtime,storage-api,imgproxy,inbucket,postgrest,pgadmin-schema-diff,migra,postgres-meta,studio,edge-runtime,logflare,vector, pgbouncer
      - run:
          name: Run the tests
          command: |
            cd supabase/functions/user-actions
            /home/circleci/.deno/bin/deno task test:coverage
      - run:
          name: Coverage
          command: |
            cd supabase/functions/user-actions
            /home/circleci/.deno/bin/deno task coverage
